.TH "test.c++" 3 "Sun Apr 15 2012" "Version 1" "test.c++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c++ \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream.h>\fP
.br
\fC#include <ctype.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.RI "\fIanother lib to use toupper \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void main ()"
.PP
another lib to use toupper 
.PP
moves char to lower case (like toupper)
.PP
puts 'grade' to a switch to cases below
.PP
inner barcket
.PP
break cuts exe at once
.PP
this points to the statement below
.PP
default 
.SH "Author"
.PP 
Generated automatically by Doxygen for test.c++ from the source code.
